### ISSUE TITLE
Fix problems reported by Clippy, add it to CI

### ISSUE THREAD

**Issue by jpschorr** [partiql/partiql-lang-rust#66]
Clippy reports a variety of style errors and suggested simplifications. We should fix them when we have the chance and make `cargo clippy` a GitHub Action so it's checked for each PR.

Example of this added to ion-rust:
- https://github.com/amzn/ion-rust/issues/348
- https://github.com/amzn/ion-rust/pull/352

**Comment by am357** [comment]
Added the CI in the following PR and resolved one of the warnings; the remaining warnings are either related to our intentional _deprecated_ annotation on  `lex_partiql` related to the lexer being a prototype or an unused function `at` in parser `Result`:
https://github.com/partiql/partiql-lang-rust/pull/73

Let's discuss further to decide if we can close or leave this open.

**Comment by am357** [comment]
Resolving this issue as we agreed it can get closed offline.
